### **Problem - 1: Array**

Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format

A single line of input containing space separated numbers.

Output Format

Print the reverse NumPy array with type float.

Sample Input

1 2 3 4 -8 -10
Sample Output

[-10.  -8.   4.   3.   2.   1.]

In [ ]:
import numpy

def arrays(arr):
    return(numpy.array(arr[::-1], float))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### **Problem-2: Shape and Reshape**
You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

Input Format

A single line of input containing  space separated integers.

Output Format

Print the X NumPy array.

Sample Input



In [ ]:
import numpy as np
l=[]
for i in range(9):
  val = int(input())
  l.append(val)
my_array = np.array(l)
print(np.reshape(my_array,(3,3)))
 

1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### **Problem-3: Transpose and Flatten**

You are given a X integer array matrix with space separated elements ( = rows and  = columns).
Your task is to print the transpose and flatten results.

Input Format

The first line contains the space separated values of  and .
The next  lines contains the space separated elements of  columns.

Output Format

First, print the transpose array and then print the flatten.

Sample Input

2 2
1 2
3 4
Sample Output

[[1 3]
 [2 4]]
[1 2 3 4]

In [ ]:
import numpy
row, col = map(int, input().split())
mat = numpy.array([input().strip().split() for i in range(row)], int)
print (mat.transpose())
print (mat.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### **Problem-4: Concatenate**
Task

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .

Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

Print the concatenated array of size X.

Sample Input

4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
Sample Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 


In [ ]:
import numpy as np
m, n, p = map(int,input().split())
val1 = np.array([input().split() for i in range(m)],int)
val2 = np.array([input().split() for i in range(n)],int)
print(np.concatenate((val1, val2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### **Problem-5: Zeros and Ones**
Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Constraints


Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

Sample Input 0

3 3 3
Sample Output 0

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
Explanation 0

Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.


In [ ]:
import numpy as np
n = tuple(map(int, input().split()))
print (np.zeros(n, dtype = np.int))
print (np.ones(n, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### **Problem - 6: Eye and Identity**

Task

Your task is to print an array of size X with its main diagonal elements as 's and 's everywhere else.

Note

In order to get alignment correct, please insert the line  below the numpy import.

Input Format

A single line containing the space separated values of  and .
 denotes the rows.
 denotes the columns.

Output Format

Print the desired X array.

Sample Input

3 3
Sample Output

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
import numpy as np
n, m = map(int, input().split())
print(np.eye(n, m))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### **Problem-7: Array Mathematics**

Task

You are given two integer arrays,  and  of dimensions X.
Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )
Note
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.

Input Format

The first line contains two space separated integers,  and .
The next  lines contains  space separated integers of array .
The following  lines contains  space separated integers of array .

Output Format

Print the result of each operation in the given order under Task.

Sample Input

1 4
1 2 3 4
5 6 7 8
Sample Output

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]] 
Use // for division in Python 3.


In [ ]:
import numpy as np
num1, num2 = map(int, input().split())
arr1, arr2 = (np.array([input().split() for i in range(num1)], dtype=int) for i in range(2))
print(arr1 + arr2, arr1 - arr2, arr1*arr2, arr1//arr2, arr1%arr2, arr1**arr2, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### **Problem - 8: Floor, Ceil and Rint**
A single line of input containing the space separated elements of array .

Output Format

On the first line, print the  of A.
On the second line, print the  of A.
On the third line, print the  of A.

Sample Input

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
Sample Output

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
import numpy

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


### **Problem-9: Sum and Prod**
Task

You are given a 2-D array with dimensions X.
Your task is to perform the  tool over axis  and then find the  of that result.

Input Format

The first line of input contains space separated values of  and .
The next  lines contains  space separated integers.

Output Format

Compute the sum along axis . Then, print the product of that sum.

Sample Input

2 2
1 2
3 4
Sample Output

24
Explanation

The sum along axis  = [ ]
The product of this sum = 


In [ ]:
import numpy as np

num1, num2 = map(int, input().split())
arr1 = np.array([input().split() for i in range(num1)],int)
print(np.prod(np.sum(arr1, axis=0), axis=0))

2 2
1 2
3 4
24


### **Problem -10: Min and Max**
Task

You are given a 2-D array with dimensions X.
Your task is to perform the min function over axis  and then find the max of that.

Input Format

The first line of input contains the space separated values of  and .
The next  lines contains  space separated integers.

Output Format

Compute the min along axis  and then print the max of that result.

Sample Input

4 2
2 5
3 7
1 3
4 0
Sample Output

3
Explanation

The min along axis  = 
The max of  = 

In [ ]:
import numpy as np

num1, num2 =map(int,input().split())

arr1=[list(map(int,input().split())) for i in range(num1)]

arr2=np.array(arr1)

print(max(np.min(arr2,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


### **Problem -11 : Mean, Var and Std**
Task

You are given a 2-D array of size X.
Your task is to find:

The mean along axis 
The var along axis 
The std along axis 
Input Format

The first line contains the space separated values of  and .
The next  lines contains  space separated integers.

Output Format

First, print the mean.
Second, print the var.
Third, print the std.

Sample Input

2 2
1 2
3 4
Sample Output

[ 1.5  3.5]
[ 1.  1.]
1.11803398875

In [1]:
import numpy as np
num1 ,num2 = map(int,input().split())
arr1 = np.array([input().split() for i in range(num1)], int)
print(arr1.mean(axis=1))
print(arr1.var(axis=0))
print(arr1.std())


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### **Problem -12: Dot and Cross**
Task

You are given two arrays  and . Both have dimensions of X.
Your task is to compute their matrix product.

Input Format

The first line contains the integer .
The next  lines contains  space separated integers of array .
The following  lines contains  space separated integers of array .

Output Format

Print the matrix multiplication of  and .

Sample Input

2
1 2
3 4
1 2
3 4
Sample Output

[[ 7 10]
 [15 22]]



In [3]:
import numpy as np

num=int(input())

arr1=np.array([list(map(int,input().split())) for i in range(num)])

arr2=np.array([list(map(int,input().split())) for i in range(num)])

print(np.dot(arr1,arr2))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### **Problem-13: Linear Algebra**
You are given a square matrix  with dimensions X. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

Input Format

The first line contains the integer .
The next  lines contains the  space separated elements of array .

Output Format

Print the determinant of .

Sample Input

2
1.1 1.1
1.1 1.1
Sample Output

0.0


In [4]:
import numpy as np

num =int(input())
arr = np.array([input().split() for i in range(num)],float)
np.set_printoptions(legacy='1.13') #important
print(np.linalg.det(arr))

2
1.1 1.1 
1.1 1.1
0.0


### **Problem-14: Polynomials**
Task

You are given the coefficients of a polynomial .
Your task is to find the value of  at point .

Input Format

The first line contains the space separated value of the coefficients in .
The second line contains the value of .

Output Format

Print the desired value.

Sample Input

1.1 2 3
0
Sample Output

3.0

In [7]:
import numpy
arr = list(map(float, input().split()))
print(numpy.polyval(arr, float(input())))

1.1 2 3
0
3.0


### **Problem - 15: Inner and Outer**

You are given two arrays:  and .
Your task is to compute their inner and outer product.

Input Format

The first line contains the space separated elements of array .
The second line contains the space separated elements of array .

Output Format

First, print the inner product.
Second, print the outer product.

Sample Input

0 1
2 3
Sample Output

3
[[0 0]
 [2 3]]

In [9]:
import numpy as np
arr1 = np.array(input().split(), int)
arr2 = np.array(input().split(), int)
print(np.inner(arr1,arr2), np.outer(arr1,arr2), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]
